# =========================
# Fonts
# =========================
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 15
disable_ligatures always

# =========================
# Cursors
# =========================
cursor                  #F2D5CF
cursor_text_color       #303446
cursor_shape beam
cursor_underline_thickness 2
cursor_blink_interval 0
cursor_stop_blinking_after 0
cursor_trail 10
cursor_trail_decay 0.1 0.5
cursor_trail_start_threshold 1
cursor_trail_duration 200
# =========================
# Scrollback
# =========================
scrollback_lines 5000

# =========================
# Mouse
# =========================
url_color                #F2D5CF
copy_on_select yes 
default_pointer_shape beam
pointer_shape_when_dragging beam
mouse_map middle release ungrabbed paste_from_selection

# =========================
# Performance
# =========================
repaint_delay 0
input_delay 0
sync_to_monitor no

# =========================
# Window layout
# =========================
enable_autowidth true
remember_window_size  no
initial_window_width  1260
initial_window_height 800
enabled_layouts *
window_resize_step_cells 1
window_resize_step_lines 1
window_border_width 0
draw_minimal_borders yes
window_margin_width 0
single_window_margin_width 0
window_padding_width 0
single_window_padding_width 0
placement_strategy center
active_border_color     #BABBF1
inactive_border_color   #737994
bell_border_color       #E5C890
hide_window_decorations no
resize_debounce_time 0.05
confirm_os_window_close 0
wayland_titlebar_color background

# =========================
# Tab bar
# =========================
tab_bar_edge bottom
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
tab_bar_style powerline
tab_bar_align left
tab_bar_min_tabs 2
tab_switch_strategy previous
tab_fade 0.25 0.5 0.75 1
tab_title_template "{num_windows} window{'s' if num_windows > 1 else ''} opened"
active_tab_foreground   #232634
active_tab_background   #000
inactive_tab_foreground #C6D0F5
inactive_tab_background #292C3C
tab_bar_background      #232634

# =========================
# Color scheme: Nordic Dark
# =========================
foreground              #D8DEE9
background              #2E3440   
selection_foreground    #2E3440
selection_background    #4C566A
background_opacity 1
background_blur 0
mark1_foreground #2E3440
mark1_background #81A1C1
mark2_foreground #2E3440
mark2_background #B48EAD
mark3_foreground #2E3440
mark3_background #88C0D0
color0  #3B4252
color8  #4C566A
color1  #BF616A
color9  #BF616A
color2  #A3BE8C
color10 #A3BE8C
color3  #EBCB8B
color11 #EBCB8B
color4  #81A1C1
color12 #81A1C1
color5  #B48EAD
color13 #B48EAD
color6  #88C0D0
color14 #88C0D0
color7  #E5E9F0
color15 #ECEFF4

# =========================
# Advanced
# =========================
allow_remote_control yes

# =========================
# Keyboard shortcuts
# =========================
clear_all_shortcuts yes
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+enter new_window
map ctrl+alt+w close_window
map ctrl+alt+l next_tab
map ctrl+alt+h previous_tab
map ctrl+alt+t new_tab
map ctrl+alt+k move_tab_forward
map ctrl+alt+j move_tab_backward
map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+backspace send_text all \x17
